apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: aqsh

build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts:
  - image: aqsh
    docker:
      dockerfile: Dockerfile
  - image: aqsh-test
    docker:
      dockerfile: Dockerfile.test

deploy:
  kubectl: {}

verify:
- name: integration-test
  container:
    name: integration-test
    image: aqsh-test
    env:
    - name: AQSH_URL
      value: http://aqsh.aqsh.svc.cluster.local:8080
  executionMode:
    kubernetesCluster: {}

manifests:
  rawYaml:
  - k8s/namespace.yaml
  - k8s/auth.yaml
  - k8s/redis.yaml
  - k8s/aqsh.yaml

profiles:
- name: remote
  build:
    local:
      push: true
    tagPolicy:
      sha256: {}
    artifacts:
    - image: registry.registry.svc.cluster.local:30500/aqsh
      docker:
        dockerfile: Dockerfile

- name: coverage
  build:
    artifacts:
    - image: aqsh
      docker:
        buildArgs:
          DEBUG: "true"
    - image: aqsh-test
      docker:
        dockerfile: Dockerfile.test
