apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aqsh.fullname" . }}-tasks-config
  labels:
    {{- include "aqsh.labels" . | nindent 4 }}
data:
  tasks.yaml: |
    {{- if .Values.tasksConfigContent }}
    {{- .Values.tasksConfigContent | nindent 4 }}
    {{- else }}
    {{- .Files.Get "files/tasks.yaml" | nindent 4 }}
    {{- end }}
