apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aqsh.fullname" . }}-task-scripts
  labels:
    {{- include "aqsh.labels" . | nindent 4 }}
data:
  {{- if .Values.scriptsContent }}
  {{- range $name, $content := .Values.scriptsContent }}
  {{ $name }}: |
    {{- $content | nindent 4 }}
  {{- end }}
  {{- else }}
  {{- range $path, $content := .Files.Glob "files/scripts/*" }}
  {{ base $path }}: |
    {{- $content | toString | nindent 4 }}
  {{- end }}
  {{- end }}
